version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # trigger the unit tests here
      - echo 'Install dependencies'
      - cd get-message-handler && npm i
      - echo 'Running unit tests'
      - npm run test
      