version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.19.1
  build:
    commands:
      # trigger the unit tests here
      - echo 'Install Dependencies & Run Test Case'
      - cd get-message-handler && npm i && npm run test

